# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 680561919e336c2b9dbba8e174c4fb5bb693a0d9e2573e9a7a42799133b851282a6acaf4bdf282d3ac9fa33faadf3cd7052d78bb52dc83c81e41fc1d0f04bce3

test:
  secret_key_base: 0e3b7ae64c8030903898d96375cfd085bcefa131a6191de45d7774c59a671203b77bcc569249d2e25a8c78cab9aa50cb69e90ded8c56bba716a971c14797ecd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
